/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.IOFile;
import controller.TrongEx;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhongHoc;
import model.QLTB;
import model.ThietBi;

/**
 *
 * @author HuyTran
 */
public class NewJFrame extends javax.swing.JFrame {

    DefaultTableModel tmTB, tmPH, tmQL;
    String fTB = "src/controller/TB.dat";
    String fPH = "src/controller/PH.dat";
    String fQL = "src/controller/QLTB.dat";
    List<ThietBi> list1 = new ArrayList<>();
    List<PhongHoc> list2 = new ArrayList<>();
    List<QLTB> list3 = new ArrayList<>();

    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        String tb[] = {"mã TB", "Tên", "Xuất xứ", "Năm sản xuất"};
        String ph[] = {"mã PH", "tên phòng", "số ghế"};
        String ql[] = {"ma PH", "ten PH", "ma TB", "ten TB", "so luong", "tinh trang"};
        tmTB = new DefaultTableModel(tb, 0);
        tmPH = new DefaultTableModel(ph, 0);
        tmQL = new DefaultTableModel(ql, 0);
        tbTable.setModel(tmTB);
        phTable.setModel(tmPH);
        qlTable.setModel(tmQL);
        loadTB();
        loadPH();
        loadQL();
        showTB();
        showPH();
        showQL();
        loadMa();
    }

    private void loadTB() {
        File f = new File(fTB);
        if (f.exists()) {
            list1 = IOFile.read(fTB);
        } else {
            IOFile.write(fTB, list1);
        }
    }

    private void loadPH() {
        File f = new File(fPH);
        if (f.exists()) {
            list2 = IOFile.read(fPH);
        } else {
            IOFile.write(fPH, list2);
        }
    }

    private void loadQL() {
        File f = new File(fQL);
        if (f.exists()) {
            list3 = IOFile.read(fQL);
        } else {
            IOFile.write(fQL, list3);
        }
    }

    private void showTB() {
        tmTB.setRowCount(0);
        for (ThietBi i : list1) {
            tmTB.addRow(i.toObjects());
        }
    }

    private void showPH() {
        tmPH.setRowCount(0);
        for (PhongHoc i : list2) {
            tmPH.addRow(i.toObjects());
        }
    }

    private void showQL() {
        tmQL.setRowCount(0);
        for (QLTB i : list3) {
            tmQL.addRow(i.toObjects());
        }
    }

    private boolean trung(int maPH, int maTB) {
        for (QLTB i : list3) {
            if (i.getPh().getMa() == maPH && i.getTb().getMa() == maTB) {
                return true;
            }
        }
        return false;
    }

    private void loadMa() {
        maPHCB.removeAllItems();
        maTBCb.removeAllItems();
        for (ThietBi i : list1) {
            maPHCB.addItem(i.getMa() + "");
        }
        for (PhongHoc i : list2) {
            maTBCb.addItem(i.getMa() + "");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        themBtn1 = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        htBtn1 = new javax.swing.JButton();
        luuBtn1 = new javax.swing.JButton();
        maTBTF = new javax.swing.JTextField();
        tenTBTF = new javax.swing.JTextField();
        xuatxuCB = new javax.swing.JComboBox<>();
        namSXTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        phTable = new javax.swing.JTable();
        maPHTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tenPHTF = new javax.swing.JTextField();
        soGheTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        luuBtn2 = new javax.swing.JButton();
        htBtn2 = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        themBtn2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        qlTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        maPHCB = new javax.swing.JComboBox<>();
        maTBCb = new javax.swing.JComboBox<>();
        sluongTF = new javax.swing.JTextField();
        ttrangTF = new javax.swing.JTextField();
        themBtn3 = new javax.swing.JButton();
        htBtn3 = new javax.swing.JButton();
        luuBtn3 = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        sortCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTable);

        jLabel1.setText("Ma TB:");

        jLabel2.setText("Ten Tb:");

        jLabel3.setText("Xuat xu:");

        jLabel4.setText("Nam sx:");

        themBtn1.setText("Them");
        themBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtn1ActionPerformed(evt);
            }
        });

        xoaBtn.setText("Xoa");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        htBtn1.setText("Hien thi");
        htBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htBtn1ActionPerformed(evt);
            }
        });

        luuBtn1.setText("Luu");
        luuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtn1ActionPerformed(evt);
            }
        });

        maTBTF.setEditable(false);

        xuatxuCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhập khẩu", "Nội địa", "Liên doanh" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tenTBTF)
                                .addComponent(maTBTF)
                                .addComponent(xuatxuCB, 0, 149, Short.MAX_VALUE))
                            .addComponent(namSXTF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(themBtn1)
                        .addGap(82, 82, 82)
                        .addComponent(xoaBtn)
                        .addGap(92, 92, 92)
                        .addComponent(htBtn1)
                        .addGap(101, 101, 101)
                        .addComponent(luuBtn1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(maTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tenTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(xuatxuCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namSXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBtn1)
                    .addComponent(xoaBtn)
                    .addComponent(htBtn1)
                    .addComponent(luuBtn1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QL Thiet Bi", jPanel1);

        phTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        phTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(phTable);

        maPHTF.setEditable(false);

        jLabel5.setText("Ma Ph:");

        jLabel6.setText("Ten ph:");

        jLabel8.setText("So Ghe:");

        luuBtn2.setText("Luu");
        luuBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtn2ActionPerformed(evt);
            }
        });

        htBtn2.setText("Hien thi");
        htBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htBtn2ActionPerformed(evt);
            }
        });

        suaBtn.setText("Sua");
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });

        themBtn2.setText("Them");
        themBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tenPHTF, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(maPHTF))
                            .addComponent(soGheTF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(themBtn2)
                        .addGap(82, 82, 82)
                        .addComponent(suaBtn)
                        .addGap(92, 92, 92)
                        .addComponent(htBtn2)
                        .addGap(101, 101, 101)
                        .addComponent(luuBtn2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(maPHTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tenPHTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(soGheTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBtn2)
                    .addComponent(suaBtn)
                    .addComponent(htBtn2)
                    .addComponent(luuBtn2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QL Phong Hoc", jPanel2);

        qlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(qlTable);

        jLabel7.setText("Ma PH:");

        jLabel9.setText("Ma TB:");

        jLabel10.setText("so luong:");

        jLabel11.setText("tinh trang:");

        maPHCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        maTBCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        themBtn3.setText("Them");
        themBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtn3ActionPerformed(evt);
            }
        });

        htBtn3.setText("Hien thi");
        htBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htBtn3ActionPerformed(evt);
            }
        });

        luuBtn3.setText("Luu");
        luuBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtn3ActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        sortCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sap xep theo:", "a. Theo tên phòng học ", "b. Theo Số lượng thiết bị mỗi loại (giảm dần" }));
        sortCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(themBtn3)
                        .addGap(99, 99, 99)
                        .addComponent(htBtn3)
                        .addGap(109, 109, 109)
                        .addComponent(luuBtn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortCB, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maPHCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maTBCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sluongTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ttrangTF, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(refreshBtn)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maPHCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maTBCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sluongTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttrangTF))
                        .addGap(48, 48, 48)
                        .addComponent(refreshBtn)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themBtn3)
                            .addComponent(htBtn3)
                            .addComponent(luuBtn3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(sortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );

        jTabbedPane1.addTab("Quan ly ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtn1ActionPerformed
        try {
            int n = list1.size();
            if (n > 0) {
                ThietBi.setSma(list1.get(n - 1).getMa() + 1);
            }
            maTBTF.setText(ThietBi.getSma() + "");
            int ma = Integer.parseInt(maTBTF.getText());
            String ten, xuatxu;
            int nam;
            ten = tenTBTF.getText();
            xuatxu = xuatxuCB.getSelectedItem().toString();
            nam = Integer.parseInt(namSXTF.getText());
            ThietBi tb = new ThietBi(ma, ten, xuatxu, nam);
            tmTB.addRow(tb.toObjects());
            list1.add(tb);
        } catch (TrongEx ex) {
            JOptionPane.showMessageDialog(this, "Khong de trong");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dien dung dinh dang");

        }
    }//GEN-LAST:event_themBtn1ActionPerformed

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        int r = tbTable.getSelectedRow();
        if (r >= 0 && r < tbTable.getRowCount()) {
            tmTB.removeRow(r);
            list1.remove(r);
        } else {
            JOptionPane.showMessageDialog(this, "Chon dung dong de xoa");

        }
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void htBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htBtn1ActionPerformed
        loadTB();
        tmTB.setRowCount(0);
        for (ThietBi i : list1) {
            tmTB.addRow(i.toObjects());
        }
    }//GEN-LAST:event_htBtn1ActionPerformed

    private void luuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtn1ActionPerformed
        IOFile.write(fTB, list1);
    }//GEN-LAST:event_luuBtn1ActionPerformed

    private void themBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtn2ActionPerformed
        try {
            int n = list2.size();
            if (n > 0) {
                PhongHoc.setSma(list2.get(n - 1).getMa() + 1);
            }
            maPHTF.setText(PhongHoc.getSma() + "");
            int ma = Integer.parseInt(maPHTF.getText());
            String ten;
            int soGhe;
            ten = tenPHTF.getText();
            soGhe = Integer.parseInt(soGheTF.getText());
            PhongHoc ph = new PhongHoc(ma, ten, soGhe);
            tmPH.addRow(ph.toObjects());
            list2.add(ph);
        } catch (TrongEx ex) {
            JOptionPane.showMessageDialog(this, "Khong de trong");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dien dung dinh dang");

        }
    }//GEN-LAST:event_themBtn2ActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        int r = phTable.getSelectedRow();
        if (r >= 0 && r < tbTable.getRowCount()) {
            try {
                int ma = Integer.parseInt(maPHTF.getText());
                String ten;
                int soGhe;
                ten = tenPHTF.getText();
                soGhe = Integer.parseInt(soGheTF.getText());
                tmPH.setValueAt(ten, r, 1);
                tmPH.setValueAt(soGhe, r, 2);
                PhongHoc ph = new PhongHoc(ma, ten, soGhe);
                list2.set(r, ph);
                JOptionPane.showMessageDialog(this, "Sua thanh cong");
            } catch (TrongEx ex) {
                JOptionPane.showMessageDialog(this, "Khong de trong");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Dien dung dinh dang");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Chon dung dong de sua");

        }
    }//GEN-LAST:event_suaBtnActionPerformed

    private void phTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phTableMouseClicked
        int r = phTable.getSelectedRow();
        if (r >= 0 && r < tbTable.getRowCount()) {
            maPHTF.setText(tmPH.getValueAt(r, 0).toString());
            tenPHTF.setText(tmPH.getValueAt(r, 1).toString());
            soGheTF.setText(tmPH.getValueAt(r, 2).toString());
        }
    }//GEN-LAST:event_phTableMouseClicked

    private void htBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htBtn2ActionPerformed
        loadPH();
        tmPH.setRowCount(0);
        for (PhongHoc i : list2)
            tmPH.addRow(i.toObjects());
    }//GEN-LAST:event_htBtn2ActionPerformed

    private void luuBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtn2ActionPerformed
        IOFile.write(fPH, list2);
    }//GEN-LAST:event_luuBtn2ActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadMa();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private PhongHoc getPH(int maPH) {
        for (PhongHoc i : list2) {
            if (i.getMa() == maPH) {
                return i;
            }
        }
        return null;
    }

    private ThietBi getTB(int maTB) {
        for (ThietBi i : list1) {
            if (i.getMa() == maTB) {
                return i;
            }
        }
        return null;
    }

    private void themBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtn3ActionPerformed
        int maPH = Integer.parseInt(maPHCB.getSelectedItem().toString());
        int maTB = Integer.parseInt(maTBCb.getSelectedItem().toString());
        if (trung(maPH, maTB)) {
            JOptionPane.showMessageDialog(this, "Da ton tai");
        } else {
            try {
                int sl = Integer.parseInt(sluongTF.getText());
                String ttrang = ttrangTF.getText();
                QLTB ql = new QLTB(getTB(maTB), getPH(maPH), sl, ttrang);
                tmQL.addRow(ql.toObjects());
                list3.add(ql);
            } catch (TrongEx ex) {
                JOptionPane.showMessageDialog(this, "Khong de trong");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Dien dung dinh dang");
            }
        }
    }//GEN-LAST:event_themBtn3ActionPerformed

    private void htBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htBtn3ActionPerformed
        tmQL.setRowCount(0);
        loadQL();
        for (QLTB i : list3)
            tmQL.addRow(i.toObjects());
    }//GEN-LAST:event_htBtn3ActionPerformed

    private void luuBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtn3ActionPerformed
        IOFile.write(fQL, list3);
    }//GEN-LAST:event_luuBtn3ActionPerformed

    private void sortCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortCBItemStateChanged
        if (sortCB.getSelectedIndex() == 1) {
            list3.sort(new Comparator<QLTB>() {
                @Override
                public int compare(QLTB o1, QLTB o2) {
                    String[] ten1 = o1.getPh().getTen().split("\\s+");
                    String[] ten2 = o2.getPh().getTen().split("\\s+");
                    if (ten1[ten1.length - 1].equals(ten2[ten2.length - 1])) {
                        return o1.getPh().getTen().compareToIgnoreCase(o2.getPh().getTen());
                    } else {
                        return ten1[ten1.length - 1].compareToIgnoreCase(ten2[ten2.length - 1]);
                    }
                }
            });
        }
        if (sortCB.getSelectedIndex() == 2) {
            Collections.sort(list3, new Comparator<QLTB>() {
                @Override
                public int compare(QLTB o1, QLTB o2) {
                    return o1.getSluong() - o2.getSluong();
                }
            });
            Collections.reverse(list3);
        }
        tmQL.setRowCount(0);
        for (QLTB i : list3) {
            tmQL.addRow(i.toObjects());
        }

    }//GEN-LAST:event_sortCBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton htBtn1;
    private javax.swing.JButton htBtn2;
    private javax.swing.JButton htBtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton luuBtn1;
    private javax.swing.JButton luuBtn2;
    private javax.swing.JButton luuBtn3;
    private javax.swing.JComboBox<String> maPHCB;
    private javax.swing.JTextField maPHTF;
    private javax.swing.JComboBox<String> maTBCb;
    private javax.swing.JTextField maTBTF;
    private javax.swing.JTextField namSXTF;
    private javax.swing.JTable phTable;
    private javax.swing.JTable qlTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField sluongTF;
    private javax.swing.JTextField soGheTF;
    private javax.swing.JComboBox<String> sortCB;
    private javax.swing.JButton suaBtn;
    private javax.swing.JTable tbTable;
    private javax.swing.JTextField tenPHTF;
    private javax.swing.JTextField tenTBTF;
    private javax.swing.JButton themBtn1;
    private javax.swing.JButton themBtn2;
    private javax.swing.JButton themBtn3;
    private javax.swing.JTextField ttrangTF;
    private javax.swing.JButton xoaBtn;
    private javax.swing.JComboBox<String> xuatxuCB;
    // End of variables declaration//GEN-END:variables
}
